// resources/js/app.js

import "./bootstrap";
import "./app-favicon";
import "./pwa-register";
import "./update-job-recommendation-history";
import "./penarikan-menu-link";
import "./penarikan-form-enhancer";
import "./update-job-withdrawn-asset-blocker";
import "./update-job-field-options";
import "./update-job-preventive-maintenance-check";
import "./command-center-import-trigger";
import "./update-job-copy-report";
import "./operational-share-report";
import "./update-job-detail-extra-fields";
import "./rental-sparepart-sidebar-link";
import "./rental-sparepart-dashboard-layout";
import "./rental-sparepart-adjustment-link";
import "./rental-sparepart-archive-ui";
import "./reminder-badge";
import "./session-switch-banner";
